POST http://localhost:3000/users/Get_User 
Content-Type: application/json

{
    "login" : "DADA",
    "password" : "Sea"
}

###

POST http://localhost:3000/users/Add_User
Content-Type: application/json

{
    "login" : "DADA",
    "password" : "Sos",
    "name" : "Даша",
    "surname" : "Басова",
    "age" : 10,
    "activiti" : 1
}

###

POST http://localhost:3000/users/Update_User 
Content-Type: application/json

{
    "password" : "Sea",
    "name" : "Беее",
    "surname" : "Вафля",
    "age" : 20,
    "activiti" : 2,
    "id" : 26
}

###

POST http://localhost:3000/lessons/Give_Lesson
Content-Type: application/json

{
    "id" : 26,
    "lesson" : 1
}

###

POST http://localhost:3000/lessons/Create_Lesson
Content-Type: application/json

{
    "userid" : 10,
    "name" : "Основы С++",
    "price" : 45
}

###

POST http://localhost:3000/videos/Add_Video
Content-Type: application/json

{
    "lesson_id" : 1,
    "url" : "Основы С#",
    "name" : "ЦК КПСС"
}

###

POST http://localhost:3000/videos/Get_Videos
Content-Type: application/json

{
    "id" : 1
}

###

POST http://localhost:3000/lessons/User_Lessons
Content-Type: application/json

{
    "id" : 26
}