POST http://localhost:3000/users/Get_User 
Content-Type: application/json

{
    "login" : "DADA",
    "password" : "Sea"
}

###

POST http://localhost:3000/users/Add_User
Content-Type: application/json

{
    "login" : "DADA",
    "password" : "Sos",
    "name" : "Даша",
    "surname" : "Басова",
    "age" : 10
}

###

POST http://localhost:3000/users/Update_User 
Content-Type: application/json

{
    "password" : "Sea",
    "name" : "Беее",
    "surname" : "Вафля",
    "age" : 20,
    "id" : 27
}

###

POST http://localhost:3000/lessons/Give_Lesson
Content-Type: application/json

{
    "id" : 26,
    "lesson" : 1
}

###

POST http://localhost:3000/lessons/Create_Lesson
Content-Type: application/json

{
    "userid" : 10,
    "name" : "Основы С++",
    "price" : 45
}

###

POST http://localhost:3000/lessons/Get_Lesson
Content-Type: application/json

{
    "id" : 2
}

###

POST http://localhost:3000/videos/Add_Video
Content-Type: application/json

{
    "lesson_id" : 1,
    "url" : "Массивы",
    "name" : "Массивы в С++"
}

###

POST http://localhost:3000/videos/Delete_Video
Content-Type: application/json

{
    "id" : 4
}

###

POST http://localhost:3000/videos/Get_Videos
Content-Type: application/json

{
    "id" : 2
}

###

POST http://localhost:3000/lessons/User_Lessons
Content-Type: application/json

{
    "id" : 26
}

###

POST http://localhost:3000/comments/Add_Comment
Content-Type: application/json

{
    "user_id" : 26,
    "lesson_id" : 1,
    "comment" : "Ужасный курс"
}

###

POST http://localhost:3000/comments/Get_Comment/By_User
Content-Type: application/json

{
    "id": 26
}

###

POST http://localhost:3000/comments/Get_Comment/By_Lesson
Content-Type: application/json

{
    "id": 1
}